AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an EC2 instance based on conditions.

Parameters:
  EnvironmentType:
    Description: Type of environment
    Type: String
    Default: Production
    AllowedValues:
      - Development
      - Production
  CreateEC2Instance:
    Description: Whether to create an EC2 instance
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro

Conditions:
  IsProduction:
    Fn::Equals:
      - Ref: EnvironmentType
      - Production
  ShouldCreateEC2Instance:
    Fn::Equals:
      - Ref: CreateEC2Instance
      - Yes
  IsProdAndCreateEC2:
    Fn::And:
      - Condition: IsProduction
      - Condition: ShouldCreateEC2Instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Condition: IsProdAndCreateEC2
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-04df9ee4d3dfde202 # Example AMI ID, replace with a valid one
      Tags:
        - Key: Name
          Value: abc
