AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: demo-key
      ImageId: ami-08a0d1e16fc3f61ea
      SecurityGroups:
        - default
   


